# Config wiki and help can be found at https://github.com/Insprill/Damage-Indicator/wiki
# For internal reference only, do not change the config version
config-version: 4

# The locale file the plugin is using. To create your own locale, copy the en-us.yml, rename it, and set its name here.
language: "en-us"

# How many decimal places to truncate indicator values
# A value of 2 means that all damage indicators will show as x.xx
indicator-decimals: 2

# How many blocks should indicators spawn above the player
# It is best to keep this value nonzero to prevent indicators
# from blocking the player's view if show-self-holograms is enabled.
hologram-offset: 0.25
# How fast should indicators float upwards
hologram-speed: 0.15
# How long (in ticks) should indicators stay for
hologram-duration: 20
# Whether the position of holograms should stay relative to the entity they came from.
relative-holograms: true

# Whether all damage indicators should be bold
bold-indicators: true

# Whether all damage indicators should be italicized
italic-indicators: false

# Whether all damage indicators should be underlined
underline-indicators: false

# Whether damage indicators should be shown.
damage-indicators: true

# Format used when players take damage
# Each damage value represents half a heart (20 points = 10 hearts)
# The closest rounded-down value will be used
damage-format:
  0: "%fefee%-%value%" # <-- The %fefee% placeholder means the indicator will show as &f-&e0&f.&e6&f9 if the player takes 0.69 damage
  2: "%f6fee%-%value%"
  4: "%fcfcc%-%value%"
  7: "%f4fcc%-%value%"
  9: "%f4f44%-%value%"
  10: "%f44fdd%-%value%"
  12: "%f55fdd%-%value%"
  100: "%rainbow%-%value%" # <-- The %rainbow% placeholder can be used to randomize indicator colors (fancy display for insta-kill tools like /kill)

# Whether damage heal indicators should be shown.
heal-indicators: true

# Format used when players heal
# Each heal value represents half a heart (20 points = 10 hearts)
# The closest rounded-down value will be used
heal-format:
  0: "%fafaa%+%value%"
  4: "%f2faa%+%value%" # <-- The %fafaa% placeholder means the indicator will show as &f+&a0&f.&a6&a9 if the player heals by 4.20 points
  8: "%f2f22%+%value%"

# Feature to display player health below their name
health-indicators: true

# DamageIndicator will not display any (damage) indicators in the following worlds
# World names are cAsE sEnSiTiVe
disabled-worlds:
  - nodelay
  - testworld

# If enabled, damage indicators will only be shown if a player caused it.
only-show-entity-damage-from-players: true

# Toggles the below entity type whitelist/blacklist.
entity-type-list-enabled: true
# If true, the following list will act as a whitelist instead of a blacklist.
entity-type-list-as-whitelist: false
entity-type-list:
  - ARMOR_STAND

# DamageIndicator will not display any (damage) indicators for entities whose name is in this list.
ignored-entities: [ ]
